server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  instance:
    hostname: gateway-10010
    prefer-ip-address: true
    instance-id: gateway
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
zuul:
  prefix: /api
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
                          
ribbon:  
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 3500 
  ConnectTimeout: 1000
